### ISSUE TITLE
Troubleshooting ValueError in flexibly_get_item()

### ISSUE THREAD

**Issue by esturdivant-usgs** [esturdivant-usgs/science-base-automation#24]
From Zafer:
```
Preview image not specified.
Preview image not specified.
Eradicated all kids from 58fe04cfe4b00749282944f5!
Traceback (most recent call last):

  File "<ipython-input-1-47194c26022b>", line 1, in <module>
    runfile('C:/Users/zdefne/Documents/PYTHON/science-base-automation/sb_automation.py', wdir='C:/Users/zdefne/Documents/PYTHON/science-base-automation')

  File "C:\Anaconda3\envs\sciencebase\lib\site-packages\spyder\utils\site\sitecustomize.py", line 866, in runfile
    execfile(filename, namespace)

  File "C:\Anaconda3\envs\sciencebase\lib\site-packages\spyder\utils\site\sitecustomize.py", line 87, in execfile
    exec(compile(scripttext, filename, 'exec'), glob, loc)

  File "C:/Users/zdefne/Documents/PYTHON/science-base-automation/sb_automation.py", line 93, in <module>
    landing_item = remove_all_files(sb, landing_id)

  File "autoSB.py", line 442, in remove_all_files
    page_id,link,item = flexibly_get_item(sb, pageid)

ValueError: too many values to unpack
```

**Comment by zdefne-usgs** [comment]
For some reason I wasn't able to update my branch from yours, so the latest version that I was working with was not the latest version in reality... 
Ok to close.
